### ISSUE TITLE
Is "Molokai" is misspelling of "Monokai"?

### ISSUE THREAD

**Issue by domainfun** [slightknack/molika-syntax#1]
The About section for this project says: "My Molokai-inspired custom syntax highlighting theme for Atom".

Did you really mean "Molokai"?

It appears that there is only a syntax highlighter called "Monokai" (with an "n"), see https://monokai.com/ - unless there is also some "Molokai" syntax highlighter I could not find?

Wikipedia says that "Molokai is the fifth most populated of the eight major islands that make up the Hawaiian Islands".

**Comment by slightknack** [comment]
Molokai is a lesser-known syntax highlighting theme loosely based on Monokai. It's been around in various incarnations for about forever: here's an older [Vim plugin](https://github.com/tomasr/molokai). It's supported in iTerm as a [color scheme](https://blog.jez.io/2014/06/07/molokai-an-iterm2-color-scheme/) too. Googling `"molokai" color scheme` turns up a number of good results :)
